version: '3.8'

networks:
  custom_net:
    driver: bridge

services:
  mongodb_meli_db:
    image: mongo:6
    container_name: mongodb_meli_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: analysis_service
    volumes:
      - mongo_data:/data/db
    networks:
      - custom_net

  config-service:
    container_name: config-service-container
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - FILE_DEFAULT_ENCODING=utf8
      - ENCRYPTION_KEY=mi_contraseña_secreta
      - AUTH_SERVICE_URL=http://auth-service:8080
      - MONGO_HOST=mongodb_meli_db
      - MONGO_PORT=27017
      - MONGO_DATABASE=analysis_service
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
    depends_on:
      - mongodb_meli_db
    networks:
      - custom_net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-service:
    container_name: auth-service-container
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - custom_net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  analysis-service:
    container_name: analysis-service-container
    build:
      context: ./analysis-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - AUTH_SERVICE_URL=http://auth-service:8080
      - CONFIG_SERVICE_URL=http://config-service:8000
      - ENCRYPTION_KEY=mi_contraseña_secreta
      - LOG_LEVEL=INFO
      - GEMINI_API_KEY=AIzaSyBw1lahxUngAHg8jHn2XvfHE-d9JUpnAp4
      - MONGO_HOST=mongodb_meli_db
      - MONGO_PORT=27017
      - MONGO_DATABASE=analysis_service
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
    depends_on:
      auth-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - custom_net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8002/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo_data:
    driver: local
